<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE symptomDatabase [

<!ELEMENT symptomDatabase (runtime+)>
<!ATTLIST symptomDatabase>

<!ELEMENT runtime (symptom+ , solution+ , directive*)>
<!ATTLIST runtime
    id ID #REQUIRED
    name CDATA #IMPLIED
    symptomUrl CDATA #IMPLIED
    localExternalFileLocation CDATA #IMPLIED>

<!ELEMENT symptom (matchPattern+)>
<!ATTLIST symptom
    id ID #REQUIRED
    description CDATA #IMPLIED
    solutions IDREFS #REQUIRED>

<!ELEMENT matchPattern EMPTY>
<!ATTLIST matchPattern
    name CDATA #IMPLIED
    value CDATA #REQUIRED>

<!ELEMENT solution EMPTY>
<!ATTLIST solution
    id ID #REQUIRED
    description CDATA #IMPLIED
    directives IDREFS #IMPLIED>

<!ELEMENT directive EMPTY>
<!ATTLIST directive
    id ID #REQUIRED
    description CDATA #IMPLIED
    directiveString CDATA #REQUIRED>
]>

<symptomDatabase>
    <runtime id="Runtime_0" name="" symptomUrl="" localExternalFileLocation="E:\symptomdb.xml">

        <!-- Symptoms: -->
	<symptom id="Symptom_0001" description="Normal exception processing from JDBC" solutions="Solution_0002">
		<!-- Wed May 15 12:28:22 2002 -->
		<!--  COM.ibm.db2.jdbc.DB2Exception com.ibm.ws.rsadapter.jdbc.WSJdbcPreparedStatement.execute 286 -->
		<matchPattern name="" value=" COM.ibm.db2.jdbc.DB2Exception "/>
		<matchPattern name="" value="COM.ibm.db2.jdbc.app.SQLExceptionGenerator.throw_SQLException"/>
		<matchPattern name="" value="COM.ibm.db2.jdbc.app.SQLExceptionGenerator.throw_SQLException"/>
		<matchPattern name="" value="COM.ibm.db2.jdbc.app.SQLExceptionGenerator.check_return_code"/>
		<matchPattern name="" value="COM.ibm.db2.jdbc.app.DB2PreparedStatement.execute2"/>
		<matchPattern name="" value="COM.ibm.db2.jdbc.app.DB2PreparedStatement.execute"/>
		<matchPattern name="" value="com.ibm.ws.rsadapter.jdbc.WSJdbcPreparedStatement.execute"/>
	</symptom>
	<symptom id="Symptom_0002" description="Query request failed to JDBC" solutions="Solution_0002">
		<!-- Wed May 15 13:12:16 2002 -->
		<!--  COM.ibm.db2.jdbc.DB2Exception com.ibm.ws.rsadapter.jdbc.WSJdbcPreparedStatement.executeQuery 371 -->
		<matchPattern name="" value=" COM.ibm.db2.jdbc.DB2Exception "/>
		<matchPattern name="" value="COM.ibm.db2.jdbc.app.SQLExceptionGenerator.throw_SQLException"/>
		<matchPattern name="" value="COM.ibm.db2.jdbc.app.SQLExceptionGenerator.throw_SQLException"/>
		<matchPattern name="" value="COM.ibm.db2.jdbc.app.SQLExceptionGenerator.check_return_code"/>
		<matchPattern name="" value="COM.ibm.db2.jdbc.app.DB2PreparedStatement.execute2"/>
		<matchPattern name="" value="COM.ibm.db2.jdbc.app.DB2PreparedStatement.executeQuery"/>
	</symptom>
	<symptom id="Symptom_0003" description="Expected exception which object does not exist" solutions="Solution_0003">
		<!-- Wed May 15 13:23:55 2002 -->
		<!--  java.rmi.NoSuchObjectException com.ibm.ejs.container.RemoteExceptionMappingStrategy.setUncheckedException 176 -->
		<matchPattern name="" value=" java.rmi.NoSuchObjectException "/>
		<matchPattern name="" value="com.ibm.ejs.container.ContainerManaged2_0BeanO.load"/>
		<matchPattern name="" value="com.ibm.ejs.container.ContainerManaged2_0BeanO.load"/>
		<matchPattern name="" value="com.ibm.ejs.container.EntityBeanO.enlist"/>
		<matchPattern name="" value="com.ibm.ejs.container.activator.OptCEntityActivationStrategy.atActivate"/>
		<matchPattern name="" value="com.ibm.ejs.container.activator.Activator.activateBean"/>
		<matchPattern name="" value="com.ibm.ejs.container.EJSContainer.preInvoke_internal"/>
		<matchPattern name="" value="com.ibm.ejs.container.EJSContainer.preInvoke"/>
		<matchPattern name="" value="com.ibm.ejs.container.EJSContainer.preInvoke"/>
	</symptom>
	<symptom id="Symptom_0004" description="" solutions="Solution_0004">
		<!-- Wed May 15 13:28:11 2002 -->
		<!--  org.omg.CORBA.OBJECT_NOT_EXIST com.ibm.ejs.container.RemoteExceptionMappingStrategy.setUncheckedException 176 -->
		<matchPattern name="" value=" org.omg.CORBA.OBJECT_NOT_EXIST "/>
		<matchPattern name="" value="com.ibm.ejs.container.ContainerManaged2_0BeanO.load"/>
		<matchPattern name="" value="com.ibm.ejs.container.ContainerManaged2_0BeanO.load"/>
		<matchPattern name="" value="com.ibm.ejs.container.EntityBeanO.enlist"/>
		<matchPattern name="" value="com.ibm.ejs.container.activator.OptCEntityActivationStrategy.atActivate"/>
		<matchPattern name="" value="com.ibm.ejs.container.activator.Activator.activateBean"/>
		<matchPattern name="" value="com.ibm.ejs.container.EJSContainer.preInvoke_internal"/>
		<matchPattern name="" value="com.ibm.ejs.container.EJSContainer.preInvoke"/>
		<matchPattern name="" value="com.ibm.ejs.container.EJSContainer.preInvoke"/>
	</symptom>
	<symptom id="Symptom_0005" description="" solutions="Solution_0005">
		<!-- Wed May 15 13:36:23 2002 -->
		<!--  COM.ibm.db2.jdbc.DB2Exception com.ibm.ws.rsadapter.jdbc.WSJdbcPreparedStatement.executeUpdate 449 -->
		<matchPattern name="" value=" COM.ibm.db2.jdbc.DB2Exception "/>
		<matchPattern name="" value="COM.ibm.db2.jdbc.app.SQLExceptionGenerator.throw_SQLException"/>
		<matchPattern name="" value="COM.ibm.db2.jdbc.app.SQLExceptionGenerator.throw_SQLException"/>
		<matchPattern name="" value="COM.ibm.db2.jdbc.app.SQLExceptionGenerator.check_return_code"/>
		<matchPattern name="" value="COM.ibm.db2.jdbc.app.DB2PreparedStatement.execute2"/>
		<matchPattern name="" value="COM.ibm.db2.jdbc.app.DB2PreparedStatement.executeUpdate"/>
		<matchPattern name="" value="com.ibm.ws.rsadapter.jdbc.WSJdbcPreparedStatement.executeUpdate"/>
	</symptom>
   	<symptom id="Symptom_0006" description="" solutions="Solution_0006">
		<!-- Wed May 15 14:25:21 2002 -->
		<!--  com.ibm.ws.rsadapter.exceptions.DataStoreAdapterException com.ibm.ws.rsadapter.cci.WSInteractionImpl.execute 201 -->
		<matchPattern name="" value=" com.ibm.ws.exception.WsException "/>
		<matchPattern name="" value="com.ibm.ws.rsadapter.exceptions.DataStoreAdapterException."/>
		<matchPattern name="" value="com.ibm.ws.rsadapter.exceptions.DataStoreAdapterException."/>
	</symptom>
	<symptom id="Symptom_0007" description="" solutions="Solution_0007">
		<!-- Wed May 15 14:31:28 2002 -->
		<!--  javax.ejb.DuplicateKeyException com.ibm.ws.ejbpersistence.dataaccess.DataAccessRequestImpl.execute 103 -->
		<matchPattern name="" value=" javax.ejb.DuplicateKeyException "/>
		<matchPattern name="" value="com.ibm.ws.rsadapter.cci.WSRelationalRAAdapter.executeCreate"/>
		<matchPattern name="" value="com.ibm.ws.ejbpersistence.dataaccess.DataAccessRequestImpl.execute"/>
		<matchPattern name="" value="com.ibm.ws.ejbpersistence.beanextensions.CBStatefulPersistor.executeCreate"/>
		<matchPattern name="" value="com.ibm.ws.ejbpersistence.beanextensions.CBStatefulPersistor.processCreate"/>
		<matchPattern name="" value="com.ibm.ws.ejbpersistence.beanextensions.CBNotExistState.ejbCreate"/>
		<matchPattern name="" value="com.ibm.ws.ejbpersistence.beanextensions.CBStatefulPersistor.ejbCreate"/>
		<matchPattern name="" value="com.ibm.ws.ejbpersistence.beanextensions.ConcreteBeanStatefulInstanceExtensionImpl.ejbCreate"/>
	</symptom>
	<symptom id="Symptom_0008" description="" solutions="Solution_0008">
		<!-- Wed May 15 14:36:26 2002 -->
		<!--  com.ibm.ws.ejbpersistence.utilpm.PMDuplicateKeyException com.ibm.ws.ejbpersistence.beanextensions.CBStatefulPersistor.executeCreate 147 -->
		<matchPattern name="" value=" com.ibm.ws.ejbpersistence.utilpm.PMDuplicateKeyException "/>
		<matchPattern name="" value="com.ibm.ws.ejbpersistence.dataaccess.DataAccessRequestImpl.execute"/>
		<matchPattern name="" value="com.ibm.ws.ejbpersistence.beanextensions.CBStatefulPersistor.executeCreate"/>
		<matchPattern name="" value="com.ibm.ws.ejbpersistence.beanextensions.CBStatefulPersistor.processCreate"/>
		<matchPattern name="" value="com.ibm.ws.ejbpersistence.beanextensions.CBNotExistState.ejbCreate"/>
		<matchPattern name="" value="com.ibm.ws.ejbpersistence.beanextensions.CBStatefulPersistor.ejbCreate"/>
		<matchPattern name="" value="com.ibm.ws.ejbpersistence.beanextensions.ConcreteBeanStatefulInstanceExtensionImpl.ejbCreate"/>
	</symptom>
	<symptom id="Symptom_0009" description="" solutions="Solution_0009">
		<!-- Wed May 15 14:44:09 2002 -->
		<!--  COM.ibm.db2.jdbc.DB2Exception com.ibm.ws.rsadapter.jdbc.WSJdbcStatement.executeQuery 459 -->
		<matchPattern name="" value=" COM.ibm.db2.jdbc.DB2Exception "/>
		<matchPattern name="" value="COM.ibm.db2.jdbc.app.SQLExceptionGenerator.throwInvalidQueryError"/>
		<matchPattern name="" value="COM.ibm.db2.jdbc.app.DB2Statement.executeQuery"/>
		<matchPattern name="" value="com.ibm.ws.rsadapter.jdbc.WSJdbcStatement.executeQuery"/>
	</symptom>
	<symptom id="Symptom_0010" description="" solutions="Solution_0010">
		<!-- Wed May 15 14:52:27 2002 -->
		<!--  COM.ibm.db2.jdbc.DB2Exception com.ibm.ws.rsadapter.jdbc.WSJdbcStatement.executeUpdate 522 -->
		<matchPattern name="" value=" COM.ibm.db2.jdbc.DB2Exception "/>
		<matchPattern name="" value="COM.ibm.db2.jdbc.app.SQLExceptionGenerator.throw_SQLException"/>
		<matchPattern name="" value="COM.ibm.db2.jdbc.app.SQLExceptionGenerator.throw_SQLException"/>
		<matchPattern name="" value="COM.ibm.db2.jdbc.app.SQLExceptionGenerator.check_return_code"/>
		<matchPattern name="" value="COM.ibm.db2.jdbc.app.DB2Statement.execute2"/>
		<matchPattern name="" value="COM.ibm.db2.jdbc.app.DB2Statement.executeUpdate"/>
		<matchPattern name="" value="com.ibm.ws.rsadapter.jdbc.WSJdbcStatement.executeUpdate"/>
	</symptom>
	<symptom id="Symptom_0011" description="" solutions="Solution_0011">
		<!-- Wed May 15 15:29:15 2002 -->
		<!--  COM.ibm.db2.jdbc.DB2Exception com.ibm.ws.rsadapter.jdbc.WSJdbcStatement.setMaxFieldSize 920 -->
		<matchPattern name="" value=" COM.ibm.db2.jdbc.DB2Exception "/>
		<matchPattern name="" value="COM.ibm.db2.jdbc.app.SQLExceptionGenerator.throwOutOfRangeError"/>
		<matchPattern name="" value="COM.ibm.db2.jdbc.app.DB2Statement.setMaxFieldSize"/>
		<matchPattern name="" value="com.ibm.ws.rsadapter.jdbc.WSJdbcStatement.setMaxFieldSize"/>
	</symptom>
	<symptom id="Symptom_0012" description="" solutions="Solution_0012">
		<!-- Wed May 15 15:32:58 2002 -->
		<!--  COM.ibm.db2.jdbc.DB2Exception com.ibm.ws.rsadapter.jdbc.WSJdbcStatement.setMaxRows 940 -->
		<matchPattern name="" value=" COM.ibm.db2.jdbc.DB2Exception "/>
		<matchPattern name="" value="COM.ibm.db2.jdbc.app.SQLExceptionGenerator.throwOutOfRangeError"/>
		<matchPattern name="" value="COM.ibm.db2.jdbc.app.DB2Statement.setMaxRows"/>
		<matchPattern name="" value="com.ibm.ws.rsadapter.jdbc.WSJdbcStatement.setMaxRows"/>
	</symptom>
	<symptom id="Symptom_0013" description="" solutions="Solution_0013">
		<!-- Wed May 15 16:05:18 2002 -->
		<!--  COM.ibm.db2.jdbc.DB2Exception com.ibm.ws.rsadapter.jdbc.WSJdbcStatement.setQueryTimeout 960 -->
		<matchPattern name="" value=" COM.ibm.db2.jdbc.DB2Exception "/>
		<matchPattern name="" value="COM.ibm.db2.jdbc.app.SQLExceptionGenerator.throwOutOfRangeError"/>
		<matchPattern name="" value="COM.ibm.db2.jdbc.app.DB2Statement.setQueryTimeout"/>
		<matchPattern name="" value="com.ibm.ws.rsadapter.jdbc.WSJdbcStatement.setQueryTimeout"/>
	</symptom>
	<symptom id="Symptom_0017" description="" solutions="Solution_0017">
		<!-- Wed May 22 11:28:10 2002 -->
		<!--  java.sql.SQLException com.ibm.ws.rsadapter.jdbc.WSJdbcResultSet.setFetchSize 2891 -->
		<matchPattern name="" value=" java.sql.SQLException "/>
		<matchPattern name="" value="COM.ibm.db2.jdbc.app.SQLExceptionGenerator.throwFetchSizeError"/>
		<matchPattern name="" value="COM.ibm.db2.jdbc.app.DB2Statement.checkFetchSize"/>
		<matchPattern name="" value="COM.ibm.db2.jdbc.app.DB2ResultSet.setFetchSize"/>
		<matchPattern name="" value="com.ibm.ws.rsadapter.jdbc.WSJdbcResultSet.setFetchSize"/>
	</symptom>
	<symptom id="Symptom_0018" description="" solutions="Solution_0018">
		<!-- Wed May 22 12:15:17 2002 -->
		<!--  java.sql.SQLException com.ibm.ws.rsadapter.jdbc.WSJdbcStatement.setFetchDirection 880 -->
		<matchPattern name="" value=" java.sql.SQLException "/>
		<matchPattern name="" value="COM.ibm.db2.jdbc.app.SQLExceptionGenerator.throwFetchDirectionError"/>
		<matchPattern name="" value="COM.ibm.db2.jdbc.app.DB2Statement.checkFetchDirection"/>
		<matchPattern name="" value="COM.ibm.db2.jdbc.app.DB2Statement.setFetchDirection"/>
		<matchPattern name="" value="com.ibm.ws.rsadapter.jdbc.WSJdbcStatement.setFetchDirection"/>
	</symptom>
    <symptom id="Symptom_0019" description="" solutions="Solution_0019">
            <!-- Wed May 22 12:31:10 2002 -->
            <!--  com.ibm.ws.security.core.AccessException com.ibm.ws.security.web.WebCollaborator.authorize 560 -->
            <matchPattern name="" value=" com.ibm.ws.security.core.AccessException "/>
            <matchPattern name="" value="com.ibm.ws.security.web.WebCollaborator.checkAuthorization"/>
            <matchPattern name="" value="com.ibm.ws.security.web.WebCollaborator.authorize"/>
            <matchPattern name="" value="com.ibm.ws.security.web.EJSWebCollaborator.preInvoke"/>
            <matchPattern name="" value="com.ibm.ws.webcontainer.webapp.WebAppSecurityCollaborator.preInvoke"/>
    </symptom>
    <symptom id="Symptom_0020" description="" solutions="Solution_0020">
            <!-- Wed May 22 12:31:17 2002 -->
            <!--  java.util.EmptyStackException com.ibm.ws.webcontainer.webapp.WebAppDispatcherContext.getCurrentServletReference 87 -->
            <matchPattern name="" value=" java.util.EmptyStackException "/>
            <matchPattern name="" value="java.util.Stack.peek"/>
            <matchPattern name="" value="com.ibm.ws.webcontainer.webapp.WebAppDispatcherContext.getCurrentServletReference"/>
            <matchPattern name="" value="com.ibm.ws.webcontainer.webapp.WebAppDispatcherResponse.getCurrentServletReference"/>
            <matchPattern name="" value="com.ibm.ws.webcontainer.webapp.WebAppDispatcherResponse.sendError"/>
            <matchPattern name="" value="com.ibm.ws.security.web.WebReply.sendError"/>
            <matchPattern name="" value="com.ibm.ws.security.web.DenyReply.writeResponse"/>
            <matchPattern name="" value="com.ibm.ws.security.web.EJSWebCollaborator.handleException"/>
            <matchPattern name="" value="com.ibm.ws.webcontainer.webapp.WebAppSecurityCollaborator.handleException"/>
    </symptom>
	<symptom id="Symptom_0021" description="" solutions="Solution_0021">
		<!-- Wed May 22 12:49:28 2002 -->
		<!--  java.util.MissingResourceException com.ibm.ejs.sm.client.ui.NLS.getString 314 -->
		<matchPattern name="" value=" java.util.MissingResourceException "/>
		<matchPattern name="" value="java.util.ResourceBundle.getObject"/>
		<matchPattern name="" value="java.util.ResourceBundle.getString"/>
		<matchPattern name="" value="com.ibm.ejs.sm.client.ui.NLS.getString"/>
		<matchPattern name="" value="com.ibm.ejs.sm.client.ui.NLS.getString"/>
	</symptom>
	<symptom id="Symptom_0022" description="" solutions="Solution_0022">
		<!-- Wed May 22 13:13:09 2002 -->
		<!--  java.util.zip.ZipException com.ibm.ws.classloader.CompoundClassLoader._defineClass 426 -->
		<matchPattern name="" value=" java.util.zip.ZipException "/>
		<matchPattern name="" value="java.util.zip.ZipFile.open"/>
		<matchPattern name="" value="java.util.zip.ZipFile."/>
		<matchPattern name="" value="java.util.jar.JarFile."/>
		<matchPattern name="" value="java.util.jar.JarFile."/>
		<matchPattern name="" value="com.ibm.ws.classloader.CompoundClassLoader._defineClass"/>
	</symptom>
	<symptom id="Symptom_0023" description="" solutions="Solution_0023">
		<!-- Wed May 22 15:31:40 2002 -->
		<!--  java.lang.IllegalStateException com.ibm.ejs.j2c.XATransactionWrapper.addSync 199 -->
		<matchPattern name="" value=" java.lang.IllegalStateException "/>
		<matchPattern name="" value="com.ibm.ejs.jts.jta.TransactionImpl.registerSynchronization"/>
		<matchPattern name="" value="com.ibm.ejs.jts.jta.JTSXA.registerSynchronization"/>
		<matchPattern name="" value="com.ibm.ejs.j2c.XATransactionWrapper.addSync"/>
		<matchPattern name="" value="com.ibm.ejs.j2c.ConnectionManager.initializeForUOW"/>
		<matchPattern name="" value="com.ibm.ejs.j2c.ConnectionManager.allocateConnection_Common"/>
		<matchPattern name="" value="com.ibm.ejs.j2c.ConnectionManager.allocateConnection"/>
		<matchPattern name="" value="com.ibm.ws.rsadapter.jdbc.WSJdbcDataSource.getConnection"/>
		<matchPattern name="" value="com.ibm.ws.rsadapter.jdbc.WSJdbcDataSource.getConnection"/>
	</symptom>
	<symptom id="Symptom_0024" description="" solutions="Solution_0024">
		<!-- Wed May 22 15:35:09 2002 -->
		<!--  javax.resource.ResourceException com.ibm.ejs.j2c.ConnectionManager.initializeForUOW 730 -->
		<matchPattern name="" value=" javax.resource.ResourceException "/>
		<matchPattern name="" value="com.ibm.ejs.j2c.XATransactionWrapper.addSync"/>
		<matchPattern name="" value="com.ibm.ejs.j2c.ConnectionManager.initializeForUOW"/>
		<matchPattern name="" value="com.ibm.ejs.j2c.ConnectionManager.allocateConnection_Common"/>
		<matchPattern name="" value="com.ibm.ejs.j2c.ConnectionManager.allocateConnection"/>
		<matchPattern name="" value="com.ibm.ws.rsadapter.jdbc.WSJdbcDataSource.getConnection"/>
		<matchPattern name="" value="com.ibm.ws.rsadapter.jdbc.WSJdbcDataSource.getConnection"/>
	</symptom>
	<symptom id="Symptom_0025" description="" solutions="Solution_0025">
		<!-- Wed May 22 15:39:56 2002 -->
		<!--  javax.ejb.EJBException com.ibm.ejs.container.BeanManagedBeanO.load 221 -->
		<matchPattern name="" value=" javax.ejb.EJBException "/>
		<matchPattern name="" value="com.ibm.ejs.container.BeanManagedBeanO.load"/>
		<matchPattern name="" value="com.ibm.ejs.container.BeanManagedBeanO.load"/>
		<matchPattern name="" value="com.ibm.ejs.container.EntityBeanO.enlist"/>
		<matchPattern name="" value="com.ibm.ejs.container.activator.OptCEntityActivationStrategy.atActivate"/>
		<matchPattern name="" value="com.ibm.ejs.container.activator.Activator.activateBean"/>
		<matchPattern name="" value="com.ibm.ejs.container.EJSContainer.preInvoke_internal"/>
		<matchPattern name="" value="com.ibm.ejs.container.EJSContainer.preInvoke"/>
		<matchPattern name="" value="com.ibm.ejs.container.EJSContainer.preInvoke"/>
	</symptom>
	<symptom id="Symptom_0026" description="" solutions="Solution_0026">
		<!-- Wed May 22 16:24:24 2002 -->
		<!--  com.ibm.ejs.container.UncheckedException com.ibm.ejs.container.RemoteExceptionMappingStrategy.setUncheckedException 176 -->
		<matchPattern name="" value=" com.ibm.ejs.container.UncheckedException "/>
		<matchPattern name="" value="com.ibm.ejs.container.BeanManagedBeanO.load"/>
		<matchPattern name="" value="com.ibm.ejs.container.BeanManagedBeanO.load"/>
		<matchPattern name="" value="com.ibm.ejs.container.EntityBeanO.enlist"/>
		<matchPattern name="" value="com.ibm.ejs.container.activator.OptCEntityActivationStrategy.atActivate"/>
		<matchPattern name="" value="com.ibm.ejs.container.activator.Activator.activateBean"/>
		<matchPattern name="" value="com.ibm.ejs.container.EJSContainer.preInvoke_internal"/>
		<matchPattern name="" value="com.ibm.ejs.container.EJSContainer.preInvoke"/>
		<matchPattern name="" value="com.ibm.ejs.container.EJSContainer.preInvoke"/>
	</symptom>
	<symptom id="Symptom_0027" description="" solutions="Solution_0027">
		<!-- Wed May 22 16:32:58 2002 -->
		<!--  javax.ejb.NoSuchEntityException com.ibm.ws.ejbpersistence.beanextensions.ConcreteBeanInstanceExtensionImpl.getRecordForLoad 705 -->
		<matchPattern name="" value=" javax.ejb.NoSuchEntityException "/>
		<matchPattern name="" value="com.ibm.ws.ejbpersistence.beanextensions.ConcreteBeanClassExtensionImpl.createPMException"/>
		<matchPattern name="" value="com.ibm.ws.ejbpersistence.beanextensions.ConcreteBeanInstanceExtensionImpl.createPMException"/>
		<matchPattern name="" value="com.ibm.ws.ejbpersistence.beanextensions.ConcreteBeanInstanceExtensionImpl.getRecordForLoad"/>
		<matchPattern name="" value="com.ibm.ws.ejbpersistence.beanextensions.CBStatefulPersistor.getRecordForLoad"/>
		<matchPattern name="" value="com.ibm.ws.ejbpersistence.beanextensions.CBStatefulPersistor.executeLoad"/>
		<matchPattern name="" value="com.ibm.ws.ejbpersistence.beanextensions.CBStatefulPersistor.processLoad"/>
		<matchPattern name="" value="com.ibm.ws.ejbpersistence.beanextensions.CBReadyState.ejbLoad"/>
		<matchPattern name="" value="com.ibm.ws.ejbpersistence.beanextensions.CBOldDirtyState.ejbLoad"/>
		<matchPattern name="" value="com.ibm.ws.ejbpersistence.beanextensions.CBStatefulPersistor.ejbLoad"/>
		<matchPattern name="" value="com.ibm.ws.ejbpersistence.beanextensions.ConcreteBeanStatefulInstanceExtensionImpl.ejbLoad"/>
		<matchPattern name="" value="com.sun.cts.tests.common.ejb.calleebeans.ConcreteCMP20CalleeEJB.ejbLoad"/>
		<matchPattern name="" value="com.ibm.ejs.container.ContainerManaged2_0BeanO.load"/>
		<matchPattern name="" value="com.ibm.ejs.container.ContainerManaged2_0BeanO.load"/>
		<matchPattern name="" value="com.ibm.ejs.container.EntityBeanO.enlist"/>
		<matchPattern name="" value="com.ibm.ejs.container.activator.OptCEntityActivationStrategy.atActivate"/>
		<matchPattern name="" value="com.ibm.ejs.container.activator.Activator.activateBean"/>
		<matchPattern name="" value="com.ibm.ejs.container.EJSContainer.preInvoke_internal"/>
		<matchPattern name="" value="com.ibm.ejs.container.EJSContainer.preInvoke"/>
	</symptom>
	<symptom id="Symptom_0028" description="" solutions="Solution_0028">
		<!-- Wed May 22 16:42:52 2002 -->
		<!--  javax.ejb.NoSuchObjectLocalException com.ibm.ejs.container.LocalExceptionMappingStrategy.setUncheckedException 172 -->
		<matchPattern name="" value=" javax.ejb.NoSuchObjectLocalException "/>
		<matchPattern name="" value="com.ibm.ejs.container.ContainerManaged2_0BeanO.load"/>
		<matchPattern name="" value="com.ibm.ejs.container.ContainerManaged2_0BeanO.load"/>
		<matchPattern name="" value="com.ibm.ejs.container.EntityBeanO.enlist"/>
		<matchPattern name="" value="com.ibm.ejs.container.activator.OptCEntityActivationStrategy.atActivate"/>
		<matchPattern name="" value="com.ibm.ejs.container.activator.Activator.activateBean"/>
		<matchPattern name="" value="com.ibm.ejs.container.EJSContainer.preInvoke_internal"/>
		<matchPattern name="" value="com.ibm.ejs.container.EJSContainer.preInvoke"/>
	</symptom>
	<symptom id="Symptom_0029" description="" solutions="Solution_0029">
		<!-- Wed May 22 17:19:52 2002 -->
		<!--  javax.ejb.ObjectNotFoundException com.ibm.ejs.container.ContainerManagedBeanO.load 536 -->
		<matchPattern name="" value=" javax.ejb.ObjectNotFoundException "/>
		<matchPattern name="" value="com.ibm.ejs.container.ContainerManagedBeanO.load"/>
		<matchPattern name="" value="com.ibm.ejs.container.ContainerManagedBeanO.load"/>
		<matchPattern name="" value="com.ibm.ejs.container.EntityBeanO.enlist"/>
		<matchPattern name="" value="com.ibm.ejs.container.activator.OptCEntityActivationStrategy.atActivate"/>
		<matchPattern name="" value="com.ibm.ejs.container.activator.Activator.activateBean"/>
		<matchPattern name="" value="com.ibm.ejs.container.EJSContainer.preInvoke_internal"/>
		<matchPattern name="" value="com.ibm.ejs.container.EJSContainer.preInvoke"/>
	</symptom>      
    <symptom id="Symptom_0030" description="" solutions="Solution_0030">
		<!-- Wed May 22 17:23:04 2002 -->
		<!--  org.omg.CORBA.OBJECT_NOT_EXIST com.ibm.ejs.container.EJSContainer.removeBean 1612 -->
		<matchPattern name="" value=" org.omg.CORBA.OBJECT_NOT_EXIST "/>
		<matchPattern name="" value="com.ibm.ejs.container.ContainerManagedBeanO.load"/>
		<matchPattern name="" value="com.ibm.ejs.container.ContainerManagedBeanO.load"/>
		<matchPattern name="" value="com.ibm.ejs.container.EntityBeanO.enlist"/>
		<matchPattern name="" value="com.ibm.ejs.container.activator.OptCEntityActivationStrategy.atActivate"/>
		<matchPattern name="" value="com.ibm.ejs.container.activator.Activator.activateBean"/>
		<matchPattern name="" value="com.ibm.ejs.container.EJSContainer.preInvoke_internal"/>
		<matchPattern name="" value="com.ibm.ejs.container.EJSContainer.preInvoke"/>
		<matchPattern name="" value="com.ibm.ejs.container.EJSContainer.removeBean"/>
		<matchPattern name="" value="com.ibm.ejs.container.EJSWrapper.remove"/>
	</symptom>
	<symptom id="Symptom_0031" description="" solutions="Solution_0031">
		<!-- Wed May 22 17:19:52 2002 -->
		<!--  javax.ejb.ObjectNotFoundException com.ibm.ejs.container.ContainerManagedBeanO.load 536 -->
		<matchPattern name="" value=" java.rmi.NoSuchObjectException "/>
		<matchPattern name="" value="com.ibm.ejs.container.ContainerManagedBeanO.load"/>
		<matchPattern name="" value="com.ibm.ejs.container.ContainerManagedBeanO.load"/>
		<matchPattern name="" value="com.ibm.ejs.container.EntityBeanO.enlist"/>
		<matchPattern name="" value="com.ibm.ejs.container.activator.OptCEntityActivationStrategy.atActivate"/>
		<matchPattern name="" value="com.ibm.ejs.container.activator.Activator.activateBean"/>
		<matchPattern name="" value="com.ibm.ejs.container.EJSContainer.preInvoke_internal"/>
		<matchPattern name="" value="com.ibm.ejs.container.EJSContainer.preInvoke"/>
	</symptom>
	<symptom id="Symptom_0032" description="" solutions="Solution_0032">
		<!-- Fri May 24 17:00:40 2002 -->
		<!--  java.rmi.NoSuchObjectException com.ibm.ejs.container.EJSHome.activateBean_Common 756 -->
		<matchPattern name="" value=" java.rmi.NoSuchObjectException "/>
		<matchPattern name="" value="com.ibm.ejs.container.ContainerManagedBeanO.load"/>
		<matchPattern name="" value="com.ibm.ejs.container.ContainerManagedBeanO.load"/>
		<matchPattern name="" value="com.ibm.ejs.container.EntityBeanO.enlist"/>
		<matchPattern name="" value="com.ibm.ejs.container.activator.OptCEntityActivationStrategy.atActivate"/>
		<matchPattern name="" value="com.ibm.ejs.container.activator.Activator.activateBean"/>
		<matchPattern name="" value="com.ibm.ejs.container.EJSContainer.activateBean"/>
		<matchPattern name="" value="com.ibm.ejs.container.EJSHome.activateBean_Common"/>
		<matchPattern name="" value="com.ibm.ejs.container.EJSHome.remove"/>
	</symptom>
	<symptom id="Symptom_0033" description="" solutions="Solution_0033">
		<!-- Fri May 24 17:00:49 2002 -->
		<!--  javax.ejb.ObjectNotFoundException com.ibm.ejs.container.EJSHome.remove 1230 -->
		<matchPattern name="" value=" javax.ejb.ObjectNotFoundException "/>
		<matchPattern name="" value="com.ibm.ejs.container.EJSHome.activateBean_Common"/>
		<matchPattern name="" value="com.ibm.ejs.container.EJSHome.remove"/>
	</symptom>
	<symptom id="Symptom_0034" description="" solutions="Solution_0034">
		<!-- Fri May 24 17:06:12 2002 -->
		<!--  javax.ejb.ObjectNotFoundException com.ibm.ws.ejbpersistence.beanextensions.ConcreteBeanInstanceExtensionImpl.getRecordForLoad 709 -->
		<matchPattern name="" value=" javax.ejb.ObjectNotFoundException "/>
		<matchPattern name="" value="com.ibm.ws.ejbpersistence.beanextensions.ConcreteBeanInstanceExtensionImpl.executeFind"/>
		<matchPattern name="" value="com.ibm.ws.ejbpersistence.beanextensions.ConcreteBeanStatefulInstanceExtensionImpl.executeFind"/>
	</symptom>
	<symptom id="Symptom_0035" description="" solutions="Solution_0035">
		<!-- Fri May 24 17:15:18 2002 -->
		<!--  com.ibm.ejs.container.BeanNotReentrantException com.ibm.ejs.container.LocalExceptionMappingStrategy.setUncheckedException 172 -->
		<matchPattern name="" value=" com.ibm.ejs.container.BeanNotReentrantException "/>
		<matchPattern name="" value="com.ibm.ejs.container.EntityBeanO.preInvoke"/>
		<matchPattern name="" value="com.ibm.ejs.container.EJSContainer.preInvoke_internal"/>
		<matchPattern name="" value="com.ibm.ejs.container.EJSContainer.preInvoke"/>
	</symptom>
	<symptom id="Symptom_0036" description="" solutions="Solution_0036">
		<!-- Fri May 24 17:15:18 2002 -->
		<!--  com.ibm.ejs.container.BeanNotReentrantException com.ibm.ejs.container.LocalExceptionMappingStrategy.setUncheckedException 172 -->
		<matchPattern name="" value=" com.ibm.ejs.container.UnknownLocalException "/>
		<matchPattern name="" value="com.ibm.ejs.container.EntityBeanO.preInvoke"/>
		<matchPattern name="" value="com.ibm.ejs.container.EJSContainer.preInvoke_internal"/>
		<matchPattern name="" value="com.ibm.ejs.container.EJSContainer.preInvoke"/>
	</symptom>
	<symptom id="Symptom_0037" description="" solutions="Solution_0037">
		<!-- Fri May 24 17:15:18 2002 -->
		<!--  com.ibm.ejs.container.BeanNotReentrantException com.ibm.ejs.container.LocalExceptionMappingStrategy.setUncheckedException 172 -->
		<matchPattern name="" value=" com.ibm.websphere.csi.CSITransactionRolledbackException "/>
		<matchPattern name="" value="com.ibm.ejs.container.EntityBeanO.preInvoke"/>
		<matchPattern name="" value="com.ibm.ejs.container.EJSContainer.preInvoke_internal"/>
		<matchPattern name="" value="com.ibm.ejs.container.EJSContainer.preInvoke"/>
	</symptom>
	<symptom id="Symptom_0038" description="" solutions="Solution_0038">
		<!-- Fri May 24 17:35:31 2002 -->
		<!--  com.ibm.websphere.csi.CSITransactionRolledbackException com.ibm.ejs.container.EJSContainer.getCurrentTx 1288 -->
		<matchPattern name="" value=" com.ibm.websphere.csi.CSITransactionRolledbackException "/>
		<matchPattern name="" value="com.ibm.ejs.csi.TransactionControlImpl.getCurrentTransactionalUOW"/>
		<matchPattern name="" value="com.ibm.ejs.container.EJSContainer.getCurrentTx"/>
		<matchPattern name="" value="com.ibm.ejs.container.EJSContainer.preInvoke_internal"/>
		<matchPattern name="" value="com.ibm.ejs.container.EJSContainer.preInvoke"/>
		<matchPattern name="" value="com.ibm.ejs.container.EJSContainer.removeBean"/>
		<matchPattern name="" value="com.ibm.ejs.container.EJSLocalWrapper.remove"/>
	</symptom>
	<symptom id="Symptom_0039" description="" solutions="Solution_0039">
		<!-- Fri May 24 17:35:31 2002 -->
		<!--  com.ibm.websphere.csi.CSITransactionRolledbackException com.ibm.ejs.container.EJSContainer.getCurrentTx 1288 -->