=== bayernmunich/IBM1/etc/wim/migration/wimdbproperty.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Begin Copyright

  Licensed Materials - Property of IBM

  Virtual Member Manager

  (C) Copyright IBM Corp. 2005 All Rights Reserved.

  US Government Users Restricted Rights - Use, duplication or
  disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

  %Z% %W% %I% %E% %U%

  End Copyright
-->
<xsd:schema targetNamespace="http://www.ibm.com/websphere/wim/wimprop" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wimprop="http://www.ibm.com/websphere/wim/wimprop"  version="1.0" elementFormDefault="qualified" attributeFormDefault="unqualified">
    
    
  <!-- ****************************** MAIN PORTION *********************************** -->

    
  <!-- Property definition -->
    

  <xsd:complexType name="EntityListType">
    <xsd:sequence>
      <xsd:element name="entityName" type="xsd:string" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>
	

  <xsd:complexType name="PropertyType">
    		

    <xsd:sequence>
      <xsd:element name="applicableEntityName" type="wimprop:EntityListType" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="requiredEntityName" type="wimprop:EntityListType" minOccurs="0" maxOccurs="1"/>
    </xsd:sequence>
    <xsd:attribute name="wimPropertyName" type="xsd:string" use="required"/>
    <xsd:attribute name="repositoryPropertyName" type="xsd:string" use="optional"/>
    <xsd:attribute name="dataType" type="xsd:string" use="required"/>
    <xsd:attribute name="classname" type="xsd:string" use="optional"/>
    <xsd:attribute name="multiValued" type="xsd:boolean" use="optional" default="true"/>
    <xsd:attribute name="readOnly" type="xsd:boolean" use="optional" default="false"/>
    <xsd:attribute name="caseExactMatch" type="xsd:boolean" use="optional" default="true"/>
    <xsd:attribute name="valueLength" type="xsd:integer" use="optional"/>
    <xsd:attribute name="metadataName" type="xsd:string" use="optional" default="DEFAULT"/>
    <xsd:attribute name="description" type="xsd:string" use="optional"/>
    <xsd:attribute name="applicationId" type="xsd:string" use="optional" default="com.ibm.websphere.wim"/>
		

  </xsd:complexType>

  <xsd:complexType name="ComponentPropertyType">
    <xsd:attribute name="wimPropertyName" type="xsd:string" use="required"/>
    <xsd:attribute name="pluginPropertyName" type="xsd:string" use="optional"/>
    <xsd:attribute name="dataType" type="xsd:string" use="required"/>
    <xsd:attribute name="classname" type="xsd:string" use="optional"/>
    <xsd:attribute name="multiValued" type="xsd:boolean" use="optional" default="true"/>
    <xsd:attribute name="readOnly" type="xsd:boolean" use="optional" default="false"/>
    <xsd:attribute name="caseExactMatch" type="xsd:boolean" use="optional" default="true"/>
    <xsd:attribute name="valueLength" type="xsd:integer" use="optional"/>
    <xsd:attribute name="description" type="xsd:string" use="optional"/>
    <xsd:attribute name="requiredInComposite" type="xsd:boolean" use="optional" default="false"/>
    <xsd:attribute name="keyInComposite" type="xsd:boolean" use="optional" default="false"/>
  </xsd:complexType>

  <xsd:complexType name="ComponentCompositePropertyType">
    <xsd:sequence>
      <xsd:element name="componentProperty" type="wimprop:ComponentPropertyType" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="wimPropertyName" type="xsd:string" use="required"/>
    <xsd:attribute name="pluginPropertyName" type="xsd:string" use="optional"/>
    <xsd:attribute name="multiValued" type="xsd:boolean" use="optional" default="true"/>
    <xsd:attribute name="readOnly" type="xsd:boolean" use="optional" default="false"/>
    <xsd:attribute name="description" type="xsd:string" use="optional"/>
    <xsd:attribute name="requiredInComposite" type="xsd:boolean" use="optional" default="false"/>
    <xsd:attribute name="keyInComposite" type="xsd:boolean" use="optional" default="false"/>
  </xsd:complexType>

    	

  <xsd:complexType name="CompositePropertyType">
    <xsd:complexContent>
      <xsd:extension base="wimprop:PropertyType">
        <xsd:sequence>
          <xsd:element name="componentProperty" type="wimprop:ComponentPropertyType" minOccurs="0" maxOccurs="unbounded"/>
          <xsd:element name="componentCompositeProperty" type="wimprop:ComponentCompositePropertyType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
    
    
  <!-- the main portion of the XML schema -->
  <xsd:element name="repositoryProperty">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="property" type="wimprop:PropertyType" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element name="compositeProperty" type="wimprop:CompositePropertyType" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="repositoryName" type="xsd:string" use="required"/>
    </xsd:complexType>
  </xsd:element>
    	

</xsd:schema>

=== bayernmunich/IBM1/etc/wim/migration/wimdbproperties_migration.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Begin Copyright

  Licensed Materials - Property of IBM

  Virtual Member Manager

  (C) Copyright IBM Corp. 2005 All Rights Reserved.

  US Government Users Restricted Rights - Use, duplication or
  disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

  %Z% %W% %I% %E% %U%

  End Copyright
-->

<wimprop:repositoryProperty repositoryName="wimDB" xmlns:wimprop="http://www.ibm.com/websphere/wim/wimprop" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ibm.com/websphere/wim/wimprop wimdbproperty.xsd ">

  <wimprop:property wimPropertyName="mail" dataType="String" valueLength="256" multiValued="false">
    <wimprop:applicableEntityName>
      <wimprop:entityName>Person</wimprop:entityName>
      <wimprop:entityName>PersonAccount</wimprop:entityName>
    </wimprop:applicableEntityName>
  </wimprop:property>
   
  <wimprop:property wimPropertyName="l" dataType="String" valueLength="256" caseExactMatch="false">
    <wimprop:applicableEntityName>
      <wimprop:entityName>Person</wimprop:entityName>
      <wimprop:entityName>PersonAccount</wimprop:entityName>
      <wimprop:entityName>OrgContainer</wimprop:entityName>
    </wimprop:applicableEntityName>
  </wimprop:property>
        
  <wimprop:property wimPropertyName="st" dataType="String" valueLength="256" caseExactMatch="false">
    <wimprop:applicableEntityName>
      <wimprop:entityName>Person</wimprop:entityName>
      <wimprop:entityName>PersonAccount</wimprop:entityName>
      <wimprop:entityName>OrgContainer</wimprop:entityName>
    </wimprop:applicableEntityName>
  </wimprop:property>
        
  <wimprop:property wimPropertyName="c" dataType="String" valueLength="256" caseExactMatch="false">
    <wimprop:applicableEntityName>
      <wimprop:entityName>Person</wimprop:entityName>
      <wimprop:entityName>PersonAccount</wimprop:entityName>
    </wimprop:applicableEntityName>
  </wimprop:property>

  <wimprop:property wimPropertyName="dc" dataType="String" valueLength="128" multiValued="false" caseExactMatch="false">
    <wimprop:applicableEntityName>
      <wimprop:entityName>OrgContainer</wimprop:entityName>
    </wimprop:applicableEntityName>
  </wimprop:property>

  <wimprop:property wimPropertyName="certificate" dataType="ByteArray" multiValued="false">
    <wimprop:applicableEntityName>
      <wimprop:entityName>PersonAccount</wimprop:entityName>
    </wimprop:applicableEntityName>
    </wimprop:property>

  <wimprop:property wimPropertyName="title" dataType="String" valueLength="128">
    <wimprop:applicableEntityName>
      <wimprop:entityName>Person</wimprop:entityName>
      <wimprop:entityName>PersonAccount</wimprop:entityName>
    </wimprop:applicableEntityName>
  </wimprop:property>

  <wimprop:compositeProperty wimPropertyName="homeAddress" dataType="Object">
    <wimprop:applicableEntityName>
      <wimprop:entityName>Person</wimprop:entityName>
      <wimprop:entityName>PersonAccount</wimprop:entityName>
    </wimprop:applicableEntityName>
    <wimprop:componentProperty wimPropertyName="nickName" dataType="String" multiValued="false" valueLength="128" requiredInComposite="true" keyInComposite="true"/>
    <wimprop:componentProperty wimPropertyName="street" dataType="String" valueLength="128" requiredInComposite="true"/>
    <wimprop:componentProperty wimPropertyName="city" dataType="String" multiValued="false" valueLength="128" requiredInComposite="true"/>
    <wimprop:componentProperty wimPropertyName="stateOrProvinceName" dataType="String" multiValued="false" valueLength="128"/>
    <wimprop:componentProperty wimPropertyName="postalCode" dataType="String" multiValued="false" valueLength="40"/>
    <wimprop:componentProperty wimPropertyName="countryName" dataType="String" multiValued="false" valueLength="128" requiredInComposite="true"/>
  </wimprop:compositeProperty>
 

  <wimprop:compositeProperty wimPropertyName="businessAddress" dataType="Object">
    <wimprop:applicableEntityName>
      <wimprop:entityName>Person</wimprop:entityName>
      <wimprop:entityName>PersonAccount</wimprop:entityName>
      <wimprop:entityName>OrgContainer</wimprop:entityName>
    </wimprop:applicableEntityName>
    <wimprop:componentProperty wimPropertyName="nickName" dataType="String" multiValued="false" valueLength="128" requiredInComposite="true" keyInComposite="true"/>
    <wimprop:componentProperty wimPropertyName="street" dataType="String" valueLength="128" requiredInComposite="true"/>
    <wimprop:componentProperty wimPropertyName="city" dataType="String" multiValued="false" valueLength="128" requiredInComposite="true"/>
    <wimprop:componentProperty wimPropertyName="stateOrProvinceName" dataType="String" multiValued="false" valueLength="128"/>
    <wimprop:componentProperty wimPropertyName="postalCode" dataType="String" multiValued="false" valueLength="40"/>
    <wimprop:componentProperty wimPropertyName="countryName" dataType="String" multiValued="false" valueLength="128" requiredInComposite="true"/>
  </wimprop:compositeProperty>
 
-->
</wimprop:repositoryProperty>
