=== bayernmunich/IBM1/systemApps/isclite.ear/isclite.war/com.ibm.ws.console.xdoperations/palettes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- IBM Confidential OCO Source Material -->
<!-- 5724-J34 (C) COPYRIGHT International Business Machines Corp. 2004 -->
<!-- The source code for this program is not published or otherwise divested -->
<!-- of its trade secrets, irrespective of what has been deposited with the -->
<!-- U.S. Copyright Office. -->



<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:annotation>
		<xsd:documentation>
		This schema defines the format for specifying color palettes.
		</xsd:documentation>
	</xsd:annotation>
	
	<xsd:element name="colorPaletteSets">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="colorPaletteSet" type="paletteSetType" minOccurs="1" maxOccurs="unbounded">
					<xsd:annotation>
						<xsd:documentation>
						A color palette set contains a number of color palettes.
						</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
			</xsd:sequence>
			<xsd:attribute name="defaultSetId" type="xsd:IDREF" use="required">
				<xsd:annotation>
				 <xsd:documentation>
				Identifier of the default palette set. Each palette definition file
				can have more than one palette sets. If the input XML does not specify
				the palette set ID, the default palette set will be used.
				 </xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="paletteSetType">
		<xsd:annotation>
			<xsd:documentation>
			A color palette set contains a number of color palettes.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="palette" type="paletteType" minOccurs="1" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:ID">
			<xsd:annotation>
			<xsd:documentation>
			Identifier of the palette set.
			 </xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="defaultPaletteId" type="xsd:IDREF" use="required">
			<xsd:annotation>
			<xsd:documentation>
			The identifier of the default palette for this palette set. If the input XML
			does not specify a palette ID, the default palette will be used.
			 </xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="paletteType">
		<xsd:attribute name="id" type="xsd:ID" use="required">
			<xsd:annotation>
			 <xsd:documentation>
			Identifier for the palette
			 </xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="colorList" type="xsd:string" use="required">
			<xsd:annotation>
			 <xsd:documentation>
			A space-delimited list of color specifications. A color can be specified by 
			a hexadecimal natation for the combination of Red, Green, and Blue color values (RGB),
			use by common color names supported by newer versions of both Netscape and Internet Explorer.
			</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>

</xsd:schema>

=== bayernmunich/IBM1/systemApps/isclite.ear/isclite.war/com.ibm.ws.console.xdoperations/palettes.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- IBM Confidential OCO Source Material -->
<!-- 5724-J34 (C) COPYRIGHT International Business Machines Corp. 2004 -->
<!-- The source code for this program is not published or otherwise divested -->
<!-- of its trade secrets, irrespective of what has been deposited with the -->
<!-- U.S. Copyright Office. -->

<colorPaletteSets defaultSetId="defaultColorPaletteSet" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="palettes.xsd">
	<colorPaletteSet defaultPaletteId="DEFAULT" id="defaultColorPaletteSet">
		<palette colorList="#0000FF #0099FF #00CC99 #00CC00 #CCCC00 #FF6600 #CC0000 #CC3399 #9933CC #00FFFF" id="DEFAULT" />
		<palette colorList="#000080 #FF1493 #228B22 #DAA520 #32CD32 #FFA500 #800080 #0000FF #8B0000 #FFD700 #808000 #FF4500 #9932CC #DC143C" id="DCCOLORS" />
		<palette colorList="#003399 #0066CC #3399FF #66CCFF #CCCCFF #9999FF #6666FF #3333FF #6699FF #99CCFF #CCFFFF #66CCCC #009999 #006666 #003366" id="SEASIDE" />
		<palette colorList="#660066 #CC0099 #FF00CC #FF66FF #FF99FF #FFCCFF #FFFFCC #FFCC99 #FF9999 #FF6666 #CC3333 #CC0000 #990033 #660033 #990099" id="SUMMER" />
		<palette colorList="#993333 #CC6633 #FF6600 #996633 #FF9900 #FFCC66 #CC9900 #999933 #CCCC00 #FFFF00 #669966 #99CC99 #336633 #669999 #99CCCC" id="EARTH" />
		<palette colorList="#99CCCC #339999 #336666 #66CCCC #CC6699 #333399 #9999FF #9966CC #9933CC #CC99CC #996699 #990099 #CC33CC #CC3399 #CC6699" id="SPRING" />
		<palette colorList="#FFCC99 #FFFFCC #FFCC33 #CC9933 #FFFF33 #CCCC00 #999900 #666600 #003300 #990033 #CC3333 #CC6666 #FF9999 #FFCCCC #CC9999" id="HARVEST" />
		<palette colorList="#CC9999 #CCCCCC #FF9999 #FFCC99 #FFCC66 #CCCC99 #FFFF99 #FFFF33 #CCFF99 #99CC99 #66CCCC #99CCCC #9999CC #996699 #CC99CC" id="PASTEL" />
	</colorPaletteSet>
</colorPaletteSets>
